### ISSUE TITLE
github pages 源分支问题

### ISSUE THREAD

**Issue by simonjoe246** [Mitscherlich/mitscherlich.me#18]
> a User or Organization Page cannot publish your site's source files from different locations.

官方文档上说个人或组织的 pages 源分支只能是 master 分支，但我看作者你的 pages 应该是在 gh_pages 分支生成的。

而且你在README上第一句话也说明了：“My personal blog based on Hexo.js and Vue.js. You can see the generated files at branch gh-pages.”

那我很好奇，你的 hexo 博客应该不是托管在 github 上吧？

**Comment by Mitscherlich** [comment]
你好。博客是托管在 github 上的，国内的镜像由 coding.net 托管。
我不太清楚现在的政策是怎样的，但在我开始使用 github 时 gh-pages 分支就是 github pages 的默认分支；当然，如果你的静态站点放在以 <username>.github.io 为名仓库下，那么 github 会默认使用 master 分支作为 github pages。
我看现在好像可以随意选择你要部署的分支，甚至可以只部署在 master 分支的 docs 文件夹下，应该算是放宽政策了吧😘

![605635c0-e73a-457a-b70e-14b47c4c9375](https://user-images.githubusercontent.com/19310241/47345150-a25db700-d6dc-11e8-948c-489e05d36d50.jpeg)

**Comment by simonjoe246** [comment]
你好，下午也看到源分支在 gh_pages 的博客了。感觉应该是政策严了，如果我理解没错的话，新建的 Pages 页面源分支只能放在 master

![](http://p2dptvml7.bkt.clouddn.com/2018-10-23%2018-34-28%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

我的 setting 界面：

![](http://p2dptvml7.bkt.clouddn.com/2018-10-23%2018-32-02%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

另外，主题很喜欢😊

**Comment by Mitscherlich** [comment]
是的，如果你从 github settings 页面直接建立 pages 默认只能部署在 master 分支上，但你可以在本地将编译好的静态文件提交到一个不同的分支或者让持续集成 (比如我就是通过 Travis CI 自动部署的) 提交到一个不同于 master 的分支，再到 settings 页面就可以选择分支了。

PS: 喜欢主题的话可以点个 star 收藏哦 🌟 ，也欢迎到我的博客看看或留言 (也许会有干货 :/)

**Comment by simonjoe246** [comment]
明白了，thank you.
